modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="surprisingloot"
version="1.20.1-1.1.0"
#logoFile="logo.png" #optional
displayName="Surprising Loot"
authors="Rinko1231"
description='''
Adds a chance for surprise mob spawns when opening loot chests, with fully customizable behavior via datapacks.
'''
